import = ["/home/phnaharris/.config/alacritty/themes/tomorrow-night.toml"]

[debug]
log_level = "Warn"
persistent_logging = false

[font]
size = 11.0

[font.bold]
family = "NotoSansM Nerd Font"
style = "Bold"

[font.bold_italic]
family = "NotoSansM Nerd Font"
style = "Bold Italic"

[font.italic]
family = "NotoSansM Nerd Font"
style = "Italic"

[font.normal]
family = "NotoSansM Nerd Font"
style = "Regular"

[window]
decorations = "full"
opacity = 1
startup_mode = "Maximized"
title = "phna@harris"

[window.position]
x = 0
y = 0
