#!/usr/bin/env bash

book=~/data/books

[ -f $book ] && readarray -t folders <$book

selected=$(find $book -iname '*.pdf' | rofi -dmenu -l 10 -p "$1")
selected=$(echo "$selected" | tr ' ' '\ ')

if [[ -z $selected ]]; then
    exit 0
fi

zathura --fork "$selected"
exit 0
