#!/bin/bash

install_programming() {
	echo "Do you want to install Haskell? (y/n)"
	read -r haskell
    echo "Do you want to install Rust? (y/n)"
    read -r rust
    # echo "Do you want to install Jetbrains Toolbox? (y/n)"
    # read -r jetbrains

	if [[ "$haskell" == "y" ]]; then
        curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
	fi

	if [[ "$rust" == "y" ]]; then
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
	fi
}

install_programming
