#!/bin/bash

install_processor_image() {
	echo "Do you have an AMD processor? (y/n)"
	read -r amd
	if [[ "$amd" == "y" ]]; then
		pacman -S amd-ucode
	fi

	echo "Do you have an Intel processor? (y/n)"
	read -r intel
	if [[ "$intel" == "y" ]]; then
		pacman -S intel-ucode
	fi
}

install_processor_image
