#!/bin/bash

location=~/Repos/dotfiles/arch/packages/program.list

package_backup() {
	all_packages=($(pacman -Qqe))
	base_devel_packages=($(pacman -Sg base-devel | cut -f 2 -d " "))
	# Removes dupes from other array
	for i in "${base_devel_packages[@]}"; do
		all_packages=(${all_packages[@]//*$i*/})
	done

	delete=(hyprland-bin hyprpaper-git hyprpicker-git waybar-hyprland intel-ucode nvidia-dkms nvidia-settings zoom alacritty tmux zsh)
	# ignore stuff I installed when installing arch
	for del in "${delete[@]}"; do
		all_packages=(${all_packages[@]//*$del*/})
	done
	printf "%s\n" "${all_packages[@]}" >$location
}

package_backup
