#!/bin/bash

location=~/Repos/dotfiles/arch/packages/program.list

package_backup() {
	all_packages=($(pacman -Qqe))
	base_devel_packages=($(pacman -Sg base-devel | cut -f 2 -d " "))
	# Removes dupes from other array
	for i in "${base_devel_packages[@]}"; do
		all_packages=(${all_packages[@]//*$i*/})
	done

	delete=(
		# codelldb-bin
		alacritty
		anydesk-bin
		archlinux-keyring
		blueman
		bolt
		brave-bin
		brightnessctl
		bun-bin
		clang
		clickhouse
		croc
		cronie
		delve
		discord
		docker
		dunst
		elixir
		eslint_d
		fcitx5
		fcitx5-configtool
		fcitx5-gtk
		fcitx5-qt
		fcitx5-unikey
		fd
		firefox
		fnm-bin
		fzf
		gimp
		git
		gnome-keyring
		go
		google-chrome
		grimblast-git
		grub
		htop
		hyprland-bin
		hyprpaper-git
		hyprpicker-git
		intel-ucode
		ly
		mongodb-bin
		mongodb-compass
		nautilus
		neofetch
		neovim
		network-manager-applet
		networkmanager
		nodejs-commitizen
		nomacs
		nvidia-dkms
		nvidia-settings
		obs-studio
		openresolv
		otf-font-awesome
		pavucontrol
		polkit-gnome
		postman-bin
		prettierd
		pulseaudio
		python-black
		qbittorrent
		qt5-wayland
		ripgrep
		shfmt
		skypeforlinux-stable-bin
		slack-desktop-wayland
		spotify
		sqlitebrowser
		sublime-text
		swappy
		swaylock
		teamviewer
		telegram-desktop
		tidy
		tlp-rdw
		tmux
		tree
		ttf-jetbrains-mono-nerd
		virt-manager
		visual-studio-code-bin
		vlc
		waybar-hyprland
		wf-recorder
		wget
		wireguard-tools
		wl-clipboard
		wlr-randr
		wofi
		xdg-desktop-portal-wlr
		zathura
		zathura-pdf-mupdf
		zoom
		zsh
	)
	# ignore stuff I installed when installing arch
	for del in "${delete[@]}"; do
		all_packages=(${all_packages[@]//*$del*/})
	done
	printf "%s\n" "${all_packages[@]}" >$location
}

package_backup
