assign [app_id="foot"] workspace number 1

assign [app_id="brave-browser"] workspace number 2
assign [app_id="TradingView"] workspace number 2

assign [app_id="org.mozilla.firefox"] workspace number 3 
assign [app_id="org.remmina.Remmina"] workspace number 3 
assign [app_id="terminal64.exe"] workspace number 3 
assign [app_id="terminal64.exe"] default_border none

assign [app_id="org.telegram.desktop"] workspace number 4
assign [app_id="signal"] workspace number 4

assign [class="obsidian"] workspace number 5

assign [app_id="org.chromium.Chromium"] workspace number 10
