#!/usr/bin/env bash

# icon: https://unicode-explorer.com/articles/cryptocurrency-unicode-symbols

# cias=$(curl https://www.cias.wtf/mk/api/summary/55555 | jq '.floorPrice')
# mias=$(curl https://www.cias.wtf/mk/api/summary/169 | jq '.floorPrice')
# bgnt=$(curl -XPOST https://api3.bigint.co/getTokenFloorAndVolume -H "Content-Type: application/json; charset=utf-8" -d '{"tickName":"bgnt"}' | jq -r '.value | .floor')

rafmafia=$(curl 'https://api.element.market/graphql?args=CollectionDetailStats' \
    -H 'authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTgxODkxNzAsImlhdCI6MTcxODEwMjc3MCwiaXNzIjoiZWxlbWVudCIsImFkZHJlc3MiOiIweDcxOGQ5YmRjMTQ1ZDg0NWRjMGQ0MTBhM2FiNDg2NGM3NGRkNDg0YTUiLCJjaGFpbk1JZCI6NzAxLCJjaGFpblNlcmllcyI6ImV0aCJ9.y0zF3tNVjpKfEVWeqsS0J7sBitoz4OTqNjtzOHvGQkE' \
    -H 'content-type: application/json' \
    -H 'cookie: JSESSIONID=88B08BFC5CA67025243E915DB2EFAA8D; cf_clearance=_QRHfpEfRMGDTekstEAZ78t_1DDRSIM2MoEYVK4IHvI-1736485996-1.2.1.1-oW_wehJGsoMnjIsWnpBhTr1msQsaaWLhd_JjQjQZOJ5ag5ncOor8O9.6v2b3hnr6ha97AP_Bd_eyVMvr25WfuPZffF195.wtoB4HKSis8nmiNAbnFTWvue4IcQo9g4VLtbIC5gBOpf9Q362OjHxw3M.OTGcIvNvyycO2ZOj7RDyFw6aH3eJbU3Zsm8DL_QiJU.Z0ZGB8QsT5y_tWsu8.YGf6D.OYbSb5s39AwUnEgsNJg5yLYa_ZqqkI6pIRjhHSzIId14pYNmNwc5RqhxPrf.o1cKEAApJslU0Mu3s0ltSEDgbszkTp0FPBfGI8W4rind.bmqi6va9WMcPohTq8.88xv9pxCN8FDnX_aF440iF02aaTQMwRDha96L6NzeGcdTbdt8jc0wIXXizSJbTAeA' \
    -H 'x-api-key: zQbYj7RhC1VHIBdWU63ki5AJKXloamDT' \
    -H 'x-api-sign: 3fcc1f1eefeff300f2e0a184b7778addae0852f210e2cdec02d416b4efb5ce4e.2472.1736485996' \
    -H 'x-query-args: CollectionDetailStats' \
    -H 'x-viewer-addr: 0x718d9bdc145d845dc0d410a3ab4864c74dd484a5' \
    -H 'x-viewer-chainmid: 2101' \
    --data-raw $'{"operationName":"CollectionDetailStats","variables":{"slug":"raf-mafia","realtime":true},"query":"query CollectionDetailStats($slug: String\u0021, $realtime: Boolean) {\\n  collection(, slug: $slug) {\\n    id\\n    name\\n    slug\\n    stats(realtime: $realtime) {\\n      nftCount\\n      ownerCount\\n      assetCount\\n      totalVolume\\n      usdTotalVolume\\n      totalListingCount\\n      coin {\\n        address\\n      }\\n      collectionBestOffer {\\n        bestOfferPriceSource\\n        paymentToken\\n      }\\n      collectionFloorPrice {\\n        floorPriceSource\\n        floorPriceUsd\\n        paymentToken\\n      }\\n      stats12H {\\n        saleCount\\n      }\\n      stats1D {\\n        avgPrice\\n        saleCount\\n        volume\\n      }\\n      stats1H {\\n        saleCount\\n      }\\n      stats15m {\\n        saleCount\\n      }\\n      range {\\n        numMax\\n        numMin\\n      }\\n    }\\n  }\\n}\\n"}')
rafmafiafp=$(echo "$rafmafia" | jq -r '.data.collection.stats.collectionFloorPrice.floorPriceSource')
rafmafiabo=$(echo "$rafmafia" | jq -r '.data.collection.stats.collectionBestOffer.bestOfferPriceSource')

FBULL=$(curl 'https://api.swap.dotwallet.com/brc20swap/swap_info' \
    --data-raw '
        {
          "send_coin_type": "cat20",
          "send_tick": "FRACTAL BULL:cc1b4c7e844c8a7163e0fccb79a9ade20b0793a2e86647825b7c05e8002b9f6a_0",
          "receive_coin_type": "fractal",
          "receive_tick": "FB",
          "address": "0"
        }' | jq -r '.data.tick2_per_tick1' | awk '{printf "%.5f", $1}')
KITTY=$(curl 'https://api.swap.dotwallet.com/brc20swap/swap_info' \
    --data-raw '
        {
          "send_coin_type": "cat20",
          "send_tick": "KittyCash:34475c0c600acf665737ef4c8d97bade02e9c5472bcfc0be141184e244d7daaf_0",
          "receive_coin_type": "fractal",
          "receive_tick": "FB",
          "address": "0"
        }' | jq -r '.data.tick2_per_tick1' | awk '{printf "%.5f", $1}')
CAT=$(curl 'https://api.swap.dotwallet.com/brc20swap/swap_info' \
    --data-raw '
        {
          "send_coin_type": "cat20",
          "send_tick": "cat:45ee725c2c5993b3e4d308842d87e973bf1951f5f7a804b21e4dd964ecd12d6b_0",
          "receive_coin_type": "fractal",
          "receive_tick": "FB",
          "address": "0"
        }' | jq -r '.data.tick2_per_tick1' | awk '{printf "%.5f", $1}')
KIBBLE=$(curl 'https://api.swap.dotwallet.com/brc20swap/swap_info' \
    --data-raw '
        {
          "send_coin_type": "cat20",
          "send_tick": "Kibble:c468e99ac3b533e503eac5ccf4f0e3362772f80cead8b7f71d802305d02f73d0_0",
          "receive_coin_type": "fractal",
          "receive_tick": "FB",
          "address": "0"
        }' | jq -r '.data.tick2_per_tick1' | awk '{printf "%.5f", $1}')
CZ=$(curl 'https://api.swap.dotwallet.com/brc20swap/swap_info' \
    --data-raw '
        {
          "send_coin_type": "cat20",
          "send_tick": "CZ:f29339845daefdcee20a543a66069e79730be8784ef5cdb8cb9ea16b752deb89_0",
          "receive_coin_type": "fractal",
          "receive_tick": "FB",
          "address": "0"
        }' | jq -r '.data.tick2_per_tick1' | awk '{printf "%.5f", $1}')
TLB=$(curl 'https://api.swap.dotwallet.com/brc20swap/swap_info' \
    --data-raw '
        {
          "send_coin_type": "cat20",
          "send_tick": "TheLonelyBit:f673cf56bfb36b189d483fa2565cacbaaf694b921af201175fbda11fdc3164b9_0",
          "receive_coin_type": "fractal",
          "receive_tick": "FB",
          "address": "0"
        }' | jq -r '.data.tick2_per_tick1' | awk '{printf "%.5f", $1}')

FB_gate=$(curl 'https://www.gate.io/apiw/v2/market/tickers/FB_USDT' | jq -r '.data.rate' | awk '{printf "%.5f", $1}')
FB_amt=821
SD_gate=$(curl 'https://www.gate.io/apiw/v2/market/tickers/SD_USDT' | jq -r '.data.rate' | awk '{printf "%.5f", $1}')
SD_amt=933
SD_usd=$(echo "scale=5; $SD_gate * $SD_amt" | bc -l | awk '{printf "%.5f\n", $0}')
FB_usd=$(echo "scale=5; $FB_gate * $FB_amt" | bc -l | awk '{printf "%.5f\n", $0}')
diff=$(echo "scale=5; $SD_usd - $FB_usd" | bc -l | awk '{printf "%.5f\n", $0}')

tFBULL="0.015 FB"
tKITTY="0.005 FB"
tCAT="0.1 FB"
tKIBBLE="0.021 FB"
tCZ="0.0157 FB"
tTLB="0.00075 FB"
# text="FBULL: $FBULL FB ($tFBULL) | KITTY: $KITTY FB ($tKITTY) | CAT: $CAT FB ($tCAT)"
text="RafMafia: $rafmafiafp - $rafmafiabo | Diff: $diff"
tooltip="FBULL: $FBULL FB ($tFBULL) \nKITTY: $KITTY FB ($tKITTY) \nCAT: $CAT FB ($tCAT) \nKIBBLE: $KIBBLE ($tKIBBLE) \nCZ: $CZ FB ($tCZ) \nTLB: $TLB FB ($tTLB)"
class=""
echo '{"text":'\""$text"\"',"tooltip":'\""$tooltip"\"',"class":'\""$class"\"'}'
