#!/usr/bin/env bash

expectedGas=$1

while true; do
    currentGas=$(curl -s 'https://mempool.fractalbitcoin.io/api/fees/recommended' | jq '.fastestFee')
    # currentGas=$(curl 'https://explorer.unisat.io/fractal-mainnet/api/bitcoin-info/fee' | jq '.data.fastestFee')
    if [ "$expectedGas" -ge "$currentGas" ]; then
        notify-send "Fractal Bitcoin current gas is $currentGas" && paplay /usr/share/sounds/freedesktop/stereo/message-new-instant.oga
    fi
    sleep 2
done
