#!/bin/bash

parent=$(
	cd "$(dirname "${BASH_SOURCE[0]}")"
	pwd -P
)
filename="program-$(date +%s).list"
location="$parent/$filename"

pkgdump() {
	touch $location
	all_packages=($(pacman -Qqe))
	base_devel_packages=($(pacman -Sg base-devel | cut -f 2 -d " "))
	# Removes dupes from other array
	for i in "${base_devel_packages[@]}"; do
		all_packages=(${all_packages[@]//*$i*/})
	done

	delete=(
		NetworkManager
		acpid
		altair
		anydesk-bin
		archlinux-keyring
		avahi-daemon
		base
		base-devel
		blueman
		bluetooth
		bolt
		brave-bin
		brightnessctl
		checkupdates-with-aur
		clang
		codelldb
		containerd
		croc
		cronie
		cronie
		cups
		delve
		dnsmasq
		docker
		docker
		dunst
		eslint_d
		eza
		fcitx5
		fcitx5-configtool
		fcitx5-gtk
		fcitx5-qt
		fcitx5-unikey
		fd
		firefox-developer-edition
		firewalld
		fish
		fstrim.timer
		fzf
		gcc
		gdb
		gimp
		git
		google-chrome
		grimblast-git
		htop
		hyprland
		hyprpaper
		hyprpicker
		intel-ucode
		keybase-bin
		latexindent
		libvirtd
		linux
		linux-firmware
		linux-headers
		ly
		ly
		man-db
		mise
		mongodb-compass
		nautilus
		neofetch
		neovim
		net-tools
		network-manager-applet
		networkmanager
		ngrok
		nodejs-commitizen
		nomacs
		noto-fonts
		nvidia
		obs-studio
		openresolv
		openssh
		otf-font-awesome
		paru
		pass
		pass-otp
		pgadmin4-py
		pipewire
		pipewire-pulse
		postman-bin
		prettierd
		proselint
		python-black
		qbittorrent
		qt5-wayland
		qt6-wayland
		rclone
		ripgrep
		rustup
		shfmt
		slack-desktop-wayland
		solaar
		sqlitebrowser
		stow
		swappy
		swaylock
		swhkd-bin
		telegram-desktop
		texlive-full
		tidy
		tlp-rdw
		tmux
		tree
		ttf-jetbrains-mono-nerd
		ttf-noto-nerd
		ufw
		unzip
		vim
		virt-manager
		vlc
		vscodium
		waybar
		wf-recorder
		wg-quick
		wget
		wireguard-tools
		wl-clipboard
		wlr-randr
		wofi
		xdg-desktop-portal-hyprland
		xfce-polkit
		zathura
		zathura-pdf-mupdf
	)
	# ignore stuff I installed when installing arch
	for del in "${delete[@]}"; do
		all_packages=(${all_packages[@]//*$del*/})
	done
	printf "%s\n" "${all_packages[@]}" >$location
}

pkgdump
find $parent -type f -name '*.list' ! -name "$filename" -delete
printf "All package was dump to $location"
