#!/usr/bin/env bash

p=$(curl 'https://api.coin-stats.com/v7/portfolio_items?coinExtraData=true&showAverage=true&excludeShowOnTotalDisabled=true&portfolioId=all-assets&visibility=personal' \
    -H 'accept: application/json, text/plain, */*' \
    -H 'accept-language: en-US,en;q=0.7' \
    -H 'if-none-match: W/"3d5b-+MfuUTew4fFQP3BHgW2doaWHQ8s"' \
    -H 'origin: https://coinstats.app' \
    -H 'platform: web' \
    -H 'priority: u=1, i' \
    -H 'referer: https://coinstats.app/' \
    -H 'sec-ch-ua: "Chromium";v="136", "Brave";v="136", "Not.A/Brand";v="99"' \
    -H 'sec-ch-ua-mobile: ?0' \
    -H 'sec-ch-ua-platform: "Linux"' \
    -H 'sec-fetch-dest: empty' \
    -H 'sec-fetch-mode: cors' \
    -H 'sec-fetch-site: cross-site' \
    -H 'sec-gpc: 1' \
    -H 'token: r:f1eb38fc72bb0ca610abb7332ee583b0' \
    -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36' \
    -H 'x-app-appearance: dark' \
    -H 'x-language-code: en' | jq .p)

pusd=$(echo "$p" | jq .USD)
pbtc=$(echo "$p" | jq .BTC)
peth=$(echo "$p" | jq .ETH)

text="Portfolio: $pusd"
tooltip="USD: $pusd \nBTC: $pbtc \nETH: $peth"
class=""
echo '{"text":'\""$text"\"',"tooltip":'\""$tooltip"\"',"class":'\""$class"\"'}'
